// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASQ-kyKLZvahm3pD_fQvR9xzV2RGuq82E',
    appId: '1:18904486721:web:8942ca1a9413e3d60747c0',
    messagingSenderId: '18904486721',
    projectId: 'apka-928bf',
    authDomain: 'apka-928bf.firebaseapp.com',
    storageBucket: 'apka-928bf.appspot.com',
    measurementId: 'G-PW6QYYZPDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60Gs-am08RKVvgz1Nfut7RNfzCV-py1E',
    appId: '1:18904486721:android:0055abbc2c9944d80747c0',
    messagingSenderId: '18904486721',
    projectId: 'apka-928bf',
    storageBucket: 'apka-928bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkkEoOT1wD5MEeZK2OcLSyG5QB6oYuQV0',
    appId: '1:18904486721:ios:fe611e715dedc0210747c0',
    messagingSenderId: '18904486721',
    projectId: 'apka-928bf',
    storageBucket: 'apka-928bf.appspot.com',
    iosClientId: '18904486721-oke0qa50icgbmr129po3nv7ihcjle0mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.apka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkkEoOT1wD5MEeZK2OcLSyG5QB6oYuQV0',
    appId: '1:18904486721:ios:fe611e715dedc0210747c0',
    messagingSenderId: '18904486721',
    projectId: 'apka-928bf',
    storageBucket: 'apka-928bf.appspot.com',
    iosClientId: '18904486721-oke0qa50icgbmr129po3nv7ihcjle0mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.apka',
  );
}
